version: v0.0.1
application:
  server_address: 0.0.0.0:10000
database:
  db_driver: mysql
  # db_source: mysql://root:codehanhan@tcp(localhost:13306)/ferry
  db_user: root
  db_password: codehanhan
  db_port: 13306
  db_name: ferry
  db_host: localhost
