version: v0.0.1
mode: dev
application:
  server_address: 0.0.0.0:10000
database:
  level: 2 # 1: Silent, 2: Error, 3: Warn, 4: Info
  driver: mysql
  user: root
  password: codehanhan
  port: 13306
  name: ferry
  host: localhost
  parse_time: true
jwt:
  secret: 326c9f73b0f45705a73eb020a32d790a
  timeout: 86400
log:
  level: info
author:
  - yangchnet
  - HT-CHEN520
