basePath: /api/v1
definitions:
  form.LoginResponse:
    properties:
      duration:
        type: integer
      token:
        type: string
    type: object
  ping.PingRecord:
    properties:
      createTime:
        type: string
      message:
        type: string
      pingID:
        type: string
      reply:
        type: string
    type: object
host: localhost:10000
info:
  contact: {}
  description: 工单系统
  title: Ferry API
  version: v0.0.1
paths:
  /login:
    get:
      consumes:
      - application/json
      description: 获取token
      operationId: user-login
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.LoginResponse'
      summary: 用户名密码登录
      tags:
      - user
  /ping/create:
    post:
      consumes:
      - application/json
      description: 接收一个字符串，返回这个字符串加上", too"后缀
      operationId: ping
      parameters:
      - description: any string
        in: query
        name: message
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 测试服务是否正常启动
      tags:
      - ping
  /ping/delete:
    delete:
      consumes:
      - application/json
      description: 接收主键PingID,根据PingID删除该条记录
      operationId: delete_ping
      parameters:
      - description: any string
        in: query
        name: ping_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除记录信息
      tags:
      - ping
  /ping/list:
    get:
      consumes:
      - application/json
      description: 接收偏移和限制量，返回对应的ping记录
      operationId: list-ping
      parameters:
      - description: 偏移量
        in: query
        name: offset
        required: true
        type: integer
      - description: 每页记录数
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ping.PingRecord'
            type: array
      summary: 分页获取ping的记录信息
      tags:
      - ping
  /ping/update:
    put:
      consumes:
      - application/json
      description: 接收主键PingID,根据PingID更新该条记录的message
      operationId: update_ping
      parameters:
      - description: any string
        in: query
        name: ping_id
        required: true
        type: string
      - description: any string
        in: query
        name: updatemessage
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 更新记录信息
      tags:
      - ping
  /user/me:
    get:
      consumes:
      - application/json
      description: 用户查看个人信息
      operationId: user-me
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 查看个人信息
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
