basePath: /api/v1
definitions:
  app.ErrResponse:
    properties:
      code:
        type: integer
      details: {}
      message:
        type: string
    type: object
  form.CaptchaResponse:
    properties:
      code:
        type: string
      data:
        type: string
      id:
        type: string
      msg:
        type: string
    type: object
  form.CreateUserResponse:
    properties:
      id:
        type: string
    type: object
  form.DeleteUserResponse:
    properties:
      result:
        type: string
    type: object
  form.ListPingResponse:
    properties:
      records:
        items:
          $ref: '#/definitions/ping.PingRecord'
        type: array
    type: object
  form.LoginResponse:
    properties:
      duration:
        type: integer
      token:
        type: string
    type: object
  form.PingResponse:
    properties:
      reply:
        type: string
    type: object
  form.ProfileResponse:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
  form.UpdatePingResponse:
    properties:
      result:
        type: string
    type: object
  form.UpdateUserResponse:
    properties:
      result:
        type: string
    type: object
  form.VerifyCaptchaResponse:
    properties:
      result:
        type: string
    type: object
  ping.PingRecord:
    properties:
      create_time:
        type: string
      message:
        type: string
      ping_id:
        type: string
      reply:
        type: string
    type: object
info:
  contact: {}
  description: 工单系统
  title: Ferry API
  version: v0.0.1
paths:
  /captcha:
    get:
      description: 获取验证码
      operationId: get-captcha
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.CaptchaResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      summary: 获取验证码
      tags:
      - captcha
    post:
      description: 验证验证码
      operationId: verify-captcha
      parameters:
      - description: 验证码id
        in: query
        name: id
        required: true
        type: string
      - description: 验证码内容
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.VerifyCaptchaResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
      summary: 验证验证码
      tags:
      - captcha
  /login:
    get:
      description: 获取token
      operationId: user-login
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 验证码id
        in: query
        name: id
        required: true
        type: string
      - description: 验证码内容
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      summary: 用户名密码登录
      tags:
      - user
  /logintest:
    get:
      description: 获取token
      operationId: user-logintest
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      summary: 用户名密码登录(测试用)
      tags:
      - user
  /ping:
    delete:
      description: 接收主键PingID,根据PingID删除该条记录
      operationId: delete_ping
      parameters:
      - description: any string
        in: query
        name: ping_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.PingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      summary: 删除记录信息
      tags:
      - ping
    get:
      description: 接收偏移和限制量，返回对应的ping记录
      operationId: list-ping
      parameters:
      - description: 偏移量
        in: query
        name: offset
        required: true
        type: integer
      - description: 每页记录数
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.ListPingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      summary: 分页获取ping的记录信息
      tags:
      - ping
    post:
      description: 接收一个字符串，返回这个字符串加上", too"后缀
      operationId: ping
      parameters:
      - description: any string
        in: query
        name: message
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.PingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      summary: 测试服务是否正常启动
      tags:
      - ping
    put:
      description: 接收主键PingID,根据PingID更新该条记录的message
      operationId: update_ping
      parameters:
      - description: any string
        in: query
        name: ping_id
        required: true
        type: string
      - description: any string
        in: query
        name: updatemessage
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.UpdatePingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      summary: 更新记录信息
      tags:
      - ping
  /user:
    delete:
      description: 管理员删除用户个人信息
      operationId: user-deletesysuser
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.DeleteUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - BearerAuth: []
      summary: 删除用户信息
      tags:
      - user
    post:
      description: 管理员创建用户个人信息
      operationId: user-createsysuser
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 角色
        in: query
        name: role
        required: true
        type: string
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.CreateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - BearerAuth: []
      summary: 创建用户信息
      tags:
      - user
  /user/adminupdateuser:
    patch:
      description: 管理员更新个人信息
      operationId: user-adminupdateuser
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      - description: 昵称
        in: query
        name: nickname
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 邮箱
        in: query
        name: email
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.UpdateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - BearerAuth: []
      summary: 管理员更新用户信息
      tags:
      - user
  /user/changepassword:
    patch:
      description: 用户更新密码
      operationId: user-changepassword
      parameters:
      - description: 旧密码
        in: query
        name: oldpassword
        required: true
        type: string
      - description: 新密码
        in: query
        name: newpassword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.UpdateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - BearerAuth: []
      summary: 用户更新密码
      tags:
      - user
  /user/me:
    get:
      description: 用户查看个人信息
      operationId: user-me
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.ProfileResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - BearerAuth: []
      summary: 查看个人信息
      tags:
      - user
  /user/updateuser:
    patch:
      description: 用户更新个人信息
      operationId: user-updateuser
      parameters:
      - description: 昵称
        in: query
        name: nickname
        type: string
      - description: 邮箱
        in: query
        name: email
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/form.UpdateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - BearerAuth: []
      summary: 更新用户信息
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
