version: "3"

services:
  ferry-db:
    image: ferry-mysql:latest
    container_name: ferry-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ~/.ferry-data/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    restart: always

  ferry-static:
    image: ferry-nginx
    container_name: ferry-static
    volumes:
      - ~/.ferry-data/nginx/data:/usr/share/nginx
      - ~/.ferry-data/nginx/log:/var/log/nginx
    ports:
      - 10081:80
    restart: always

  ferry-main:
    image: ferry-main:latest
    container_name: ferry-main
    ports:
      - 10001:10000
    restart: on-failure
    depends_on:
      - ferry-db
      - ferry-static

  ferry-migrate:
    image: migrate/migrate
    container_name: ferry-migrate
    depends_on:
      - ferry-db
    volumes:
      - ../../db/schema:/database
    command:
      [
        "-path",
        "/database",
        "-database",
        "mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(ferry-db:3306)/ferry?parseTi\
          me=true",
        "up"
      ]
    restart: on-failure
